version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodatadb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: lanchonete
    networks:
      - mybridge
volumes:
  mongodatadb:
    name: mongodata-volume
networks:
  mybridge:
    driver: bridge