spring:
  data:
    mongodb:
      authentication-database: admin
      database: lanchonete
      username: username
      password: password
      host: ${DATABASE_HOST:localhost}
      port: 27017
  jackson:
    deserialization:
      fail-on-unknown-properties: false
server:
  servlet:
    context-path: /lanchonete-pedidos/api/v1

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

integration:
  mercado-pago:
    service: ${MERCADO_PAGO_SERVICE:https://api.mercadopago.com}
    enabled: ${MERCADO_PAGO_ENABLED:false}
    bearer-token: TEST-??????????-??????????-??????????
    collector-id: ??????????
    pos-id: SUC001POSSUC001001
  cliente:
    service: ${CLIENTE_SERVICE:localhost:8090/lanchonete-cliente/api/v1}
  produto:
    service: ${PRODUTO_SERVICE:localhost:9090/lanchonete-produto/api/v1}

app:
  mq:
    port: ${MQ_PORT:5672}
    cliente:
      username: ${CLIENT_MQ_USERNAME:guest}
      password: ${CLIENT_MQ_PASSWORD:src/main/resources/etc/credential/secret-password-broker-mq-queue}
      brokerURL: ${CLIENT_MQ_HOST:localhost}
      queueName: ${CLIENT_MQ_QUEUE_NAME:pedido-to-client-mq}
    cozinha:
      username: ${COZINHA_MQ_USERNAME:guest}
      password: ${COZINHA_MQ_PASSWORD:src/main/resources/etc/credential/secret-password-broker-mq-queue}
      brokerURL: ${COZINHA_MQ_HOST:localhost}
      queueName: ${COZINHA_MQ_QUEUE_NAME:pedido-to-cozinha-mq}