spring:
  data:
    mongodb:
      authentication-database: admin
      database: lanchonete
      username: user
      password: password
      host: localhost
      port: 27017
  jackson:
    deserialization:
      fail-on-unknown-properties: false
server:
  servlet:
    context-path: /lanchonete-pedidos/api/v1

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

integration:
  mercado-pago:
    service: ${MERCADO_PAGO_SERVICE:https://api.mercadopago.com}
    enabled: ${MERCADO_PAGO_ENABLED:false}
    bearer-token: TEST-??????????-??????????-??????????
    collector-id: ??????????
    pos-id: SUC001POSSUC001001
  cliente:
    service: ${CLIENTE_SERVICE:localhost:8090/lanchonete/api/v1}
  produto:
    service: ${PRODUTO_SERVICE:localhost:8090/lanchonete/api/v1}