apiVersion: v1
kind: Service
metadata:
  name: {{ include "lanchonete-pedido.fullname" . }}
  labels:
    {{- include "lanchonete-pedido.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "lanchonete-pedido.selectorLabels" . | nindent 4 }}
